spring:

  thymeleaf:

    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elec5619?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

    hikari:

      pool-name: DataHikariCP

      minimum-idle: 5

      idle-timeout: 1800000

      maximum-pool-size: 10

      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000

      connection-test-query: SESECT 1

mybatis-plus:

  mapper-location: classpath*:xml/*Mapper.xml

  type-aliases-package: com.elec.dal.pojo


